name: fam-exercises
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
library:
  source-dirs: src
  exposed-modules:
    - FAMExamples
    - ParserExamples
tests:
  FunctorLawsTest:
    main: FunctorLawsTest.hs
    source-dirs: test
    ghc-options: "-Wall -main-is FunctorLawsTest"
    dependencies:
      - fam-exercises
      - QuickCheck
  ParserExample:
    main: ParserExample.hs
    source-dirs: test
    ghc-options: "-Wall -main-is ParserExample"
    dependencies:
      - fam-exercises
