name: lazy-par-con-exercises
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - parallel
  - stm
library:
  source-dirs: src
  exposed-modules:
    - Lazy
    - Parallel
    - Concurrency
tests:
  LazyTest:
    main: LazyTest.hs
    source-dirs: test
    ghc-options: "-Wall -main-is LazyTest"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
  ParallelTest:
    main: ParallelTest.hs
    source-dirs: test
    ghc-options: "-Wall -main-is ParallelTest"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
  ConcurrencyTest:
    main: ConcurrencyTest.hs
    source-dirs: test
    ghc-options: "-Wall -main-is ConcurrencyTest"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
