name: lazy-par-con-exercises
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - parallel
  - stm
library:
  source-dirs: src
  exposed-modules:
    - LazyExamples
    - ParallelExamples
    - ConcurrencyExamples
tests:
  LazyExample:
    main: LazyExample.hs
    source-dirs: test
    ghc-options: "-Wall -main-is LazyExample"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
  ParallelExample:
    main: ParallelExample.hs
    source-dirs: test
    ghc-options: "-Wall -main-is ParallelExample"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
  ConcurrencyExample:
    main: ConcurrencyExample.hs
    source-dirs: test
    ghc-options: "-Wall -main-is ConcurrencyExample"
    dependencies:
      - lazy-par-con-exercises
      - QuickCheck
