name: lazy-par-con-exercises
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - deepseq
  - parallel
library:
  source-dirs: src
  exposed-modules:
    - Exercises.LazyParCon.LazyExamples
    - Exercises.LazyParCon.ParallelExamples
    - Exercises.LazyParCon.ConcurrencyExamples
tests:
  LazyExample:
    main: test/LazyExample.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - lazy-par-con-exercises
  ParallelExample:
    main: test/ParallelExample.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - lazy-par-con-exercises
  ConcurrencyExample:
    main: test/ConcurrencyExample.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - lazy-par-con-exercises
