name: memoization-trie-exercises
version: 0.1.0.0
dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
library:
  source-dirs: src
  exposed-modules:
    - Memoization
tests:
  MemoizationTest:
    main: MemoizationTest.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - memoization-trie-exercises
      - QuickCheck
